spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university
    username: myuser
    password: mypass

server:
  port: 8082

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
